name: Extension CI

defaults:
  run:
    shell: bash
    working-directory: ./chrome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci .
          
      - name: Check formatting with Prettier
        run: npx prettier --check .
        
      - name: Lint with ESLint
        run: npx eslint .
        
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci .
      
      - name: Run web-ext lint
        run: npx web-ext lint .
        
      - name: Run Mozilla's addon-lint
        run: npx addons-linter .
        
  build:
    runs-on: ubuntu-latest
    needs: [lint-and-format, security-checks]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci .
      
      - name: Build extension
        run: ./chrome/build.sh
